version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - app_network

  routing_service:
    build: ./routing_service
    ports:
      - "8000:8000"
    volumes:
      - ./persistent_storage:/persistent_storage # Correct mount path
    depends_on:
      - inference_service_model1
      - inference_service_model2
      - inference_service_model3
      - inference_service_model4
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - app_network

  inference_service_model1:
    build: ./inference_services/model1
    ports:
      - "8001:8000"
    volumes:
      - ./persistent_storage:/persistent_storage # Correct mount path
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - app_network

  inference_service_model2:
    build: ./inference_services/model2
    ports:
      - "8002:8000"
    volumes:
      - ./persistent_storage:/persistent_storage # Correct mount path
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - app_network

  inference_service_model3:
    build: ./inference_services/model3
    ports:
      - "8003:8000"
    volumes:
      - ./persistent_storage:/persistent_storage # Correct mount path
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - app_network

  inference_service_model4:
    build: ./inference_services/model4
    ports:
      - "8004:8000"
    volumes:
      - ./persistent_storage:/persistent_storage # Correct mount path
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - app_network

  fine_tuning_service:
    build: ./fine_tuning_service
    ports:
      - "8005:8000"
    volumes:
      - ./persistent_storage:/persistent_storage # Correct mount path
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - app_network
