---
- name: Deploy NST_app to Kubernetes
  hosts: local
  gather_facts: no

  tasks:
    - name: Ensure namespace `default` exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: default
        state: present

    - name: Apply PersistentVolume
      kubernetes.core.k8s:
        state: present
        src: "{{ k8s_manifests_dir }}/persistent-volumes/pv.yaml"

    - name: Apply PersistentVolumeClaim
      kubernetes.core.k8s:
        state: present
        src: "{{ k8s_manifests_dir }}/persistent-volumes/pvc.yaml"
        namespace: default

    - name: Apply all deployment manifests
      kubernetes.core.k8s:
        state: present
        src: "{{ item }}"
        namespace: default
      with_fileglob:
        - "{{ k8s_manifests_dir }}/deployments/*.yaml"

    - name: Apply all service manifests
      kubernetes.core.k8s:
        state: present
        src: "{{ item }}"
        namespace: default
      with_fileglob:
        - "{{ k8s_manifests_dir }}/services/*.yaml"

    - name: Apply ingress
      kubernetes.core.k8s:
        state: present
        src: "{{ k8s_manifests_dir }}/ingress/ingress.yaml"
        namespace: default

    - name: Gather all Pod objects in `default`
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: default
      register: pod_list

    - name: Extract Pod names into a simple list
      set_fact:
        pod_names: "{{ pod_list.resources | map(attribute='metadata.name') | list }}"

    - name: Wait for each Pod to become Ready
      shell: |
        kubectl wait --for=condition=Ready pod/{{ item }} \
          --namespace=default --timeout=120s
      loop: "{{ pod_names }}"
      when: >
        (pod_list.resources
         | selectattr('metadata.name','equalto',item)
         | map(attribute='status.phase')
         | first) != 'Succeeded'
