apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-service-model2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-service-model2
  template:
    metadata:
      labels:
        app: inference-service-model2
    spec:
      containers:
        - name: inference-service-model2
          image: deepanshu0903/nst_app:inference_service_model2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: model-storage
              mountPath: /persistent_storage
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: nst-pvc
