# filepath: /home/deepanshu/Documents/SPE Major/NST_app/kubernetes/persistent-volumes/pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nst-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /persistent_storage # Specify the directory on the Minikube VM
    type: DirectoryOrCreate