# filepath: /home/deepanshu/Documents/SPE Major/NST_app/kubernetes/persistent-volumes/pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nst-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/persistent_storage" # Ensure this matches the Minikube mount path
  persistentVolumeReclaimPolicy: Retain