apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nst-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: nst-pv
  storageClassName: ""   # Match the PV
