apiVersion: v1
kind: Service
metadata:
  name: fine-tuning-service
spec:
  type: NodePort
  selector:
    app: fine-tuning-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30002 # Optional: Specify a custom NodePort
