apiVersion: v1
kind: Service
metadata:
  name: routing-service
spec:
  type: ClusterIP  # Ensure internal routing
  selector:
    app: routing-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
