apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
    processors:
      - add_kubernetes_metadata:
          in_cluster: true

    output.logstash:
      hosts: ["logstash.elk.svc.cluster.local:5044"]
